<template>
  <v-container class="pa-6 mx-auto" style="max-width: 1280px;">
    <!-- HEADER -->
    <div class="d-flex align-center justify-space-between mb-6">
      <div>
        <div class="text-caption text-grey font-weight-bold">// TEST CYCLES</div>
        <div class="text-h5 font-weight-bold">Test Cycles</div>
      </div>
      <div v-if="apiLoading" class="text-caption text-blue mb-2">Loading data from the server.</div>
      <v-btn color="primary" prepend-icon="mdi-plus" @click="openCreateDialog">
        New Test Cycle
      </v-btn>
    </div>

   
    <v-card variant="outlined" class="rounded-xl">
      <v-data-table
        :headers="headers"
        :items="cyclesList"
        :loading="apiLoading"
        class="elevation-0"
      >
        <template v-slot:item.status="{ item }">
          <v-chip :color="getStatusColor(item.status)" size="small" label>
            {{ item.status }}
          </v-chip>
        </template>

        <template v-slot:item.totalCases="{ item }">
          <span 
            class="text-primary font-weight-bold text-decoration-underline cursor-pointer"
            @click="goToTestCases(item.id)"
          >
            0
          </span>
        </template>

        <template v-slot:item.auto_assign_rule="{ item }">
          <v-chip size="small" color="grey-lighten-2" label>
            {{ item.auto_assign_rule || 'None' }}
          </v-chip>
        </template>

        <template v-slot:item.assigned_to_name="{ item }">
          <span class="text-caption font-weight-medium">{{ item.assigned_to_name || 'Unassigned' }}</span>
        </template>

        <template v-slot:item.actions="{ item }">
          <v-btn icon size="small" variant="text" color="blue" @click="openEditDialog(item)">
            <v-icon size="small">mdi-pencil</v-icon>
          </v-btn>
          <v-btn icon size="small" variant="text" color="red" @click="confirmDelete(item)">
            <v-icon size="small">mdi-delete</v-icon>
          </v-btn>
        </template>

        <template v-slot:no-data>
          <div class="text-center text-grey pa-8">No test cycles available.</div>
        </template>
      </v-data-table>
    </v-card>

    
    <v-dialog v-model="dialog" max-width="600px" persistent>
      <v-card class="rounded-xl">
        <v-card-title class="text-white pa-4 d-flex align-center justify-space-between" style="background-color: #1e293b;">
          <span class="text-h6 font-weight-bold">{{ isEditing ? 'Edit Test Cycle' : 'New Test Cycle' }}</span>
          <v-btn icon variant="text" size="small" @click="dialog = false">
            <v-icon color="white">mdi-close</v-icon>
          </v-btn>
        </v-card-title>

        <v-card-text class="pa-6">
          <v-container class="pa-0">
            <v-row density="compact">
              <v-col cols="12">
                <v-text-field
                  v-model="cycleForm.cycleId"
                  label="Cycle ID"
                  variant="outlined"
                  density="compact"
                  placeholder="Auto-generated by system"
                  disabled
                  class="text-grey font-weight-bold"
                ></v-text-field>
              </v-col>
            </v-row>
            <v-row density="compact">
              <v-col cols="12">
                <v-combobox
                  v-model="cycleForm.name"
                  label="Version Tag"
                  :items="versionTagOptions"
                  variant="outlined"
                  density="compact"
                  placeholder="Choose a version or type a new one..."
                  required
                  clearable
                ></v-combobox>
              </v-col>
            </v-row>
            <v-row density="compact">
              <v-col cols="12">
                <v-select
                  v-model="cycleForm.department"
                  :items="departmentOptions"
                  label="Department (Code)"
                  variant="outlined"
                  density="compact"
                  placeholder="Choose Department Code..."
                  clearable
                ></v-select>
              </v-col>
            </v-row>
            <v-row density="compact">
              <v-col cols="12" sm="6">
                <v-text-field
                  v-model="cycleForm.dtStart"
                  label="Start Date"
                  type="date"
                  variant="outlined"
                  density="compact"
                ></v-text-field>
              </v-col>
              <v-col cols="12" sm="6">
                <v-text-field
                  v-model="cycleForm.dtEnd"
                  label="End Date"
                  type="date"
                  variant="outlined"
                  density="compact"
                ></v-text-field>
              </v-col>
            </v-row>

            <v-row density="compact">
              <v-col cols="12" sm="6">
                <v-select
                  v-model="cycleForm.status"
                  :items="['Active', 'Completed']"
                  label="Status"
                  variant="outlined"
                  density="compact"
                ></v-select>
              </v-col>
              <v-col cols="12" sm="6">
                <v-text-field
                  v-model="cycleForm.createdDate"
                  label="Created Date"
                  type="date"
                  variant="outlined"
                  density="compact"
                  disabled
                ></v-text-field>
              </v-col>
            </v-row>
            <v-row density="compact">
              <v-col cols="12">
                <v-select
                  v-model="cycleForm.autoAssignRule"
                  :items="autoAssignOptions"
                  label="Auto-Assign Rule (untuk Test Cases)"
                  variant="outlined"
                  density="compact"
                  placeholder="Choose rule auto-assign..."
                  clearable
                ></v-select>
              </v-col>
            </v-row>
          </v-container>
        </v-card-text>

        <v-card-actions class="pa-4 border-t">
          <v-spacer></v-spacer>
          <v-btn variant="text" @click="dialog = false" class="text-capitalize">Cancel</v-btn>
          <v-btn color="primary" class="px-6 rounded-lg text-capitalize" @click="saveCycle">
            {{ isEditing ? 'Update' : 'Save' }}
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    
    <v-dialog v-model="deleteDialog" max-width="400px">
      <v-card class="rounded-xl pa-2">
        <v-card-title class="font-weight-bold">Delete Test Cycle?</v-card-title>
        <v-card-text>
          Are you sure you want to delete <b>"{{ deleteTarget?.name }}"</b>?
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn variant="text" @click="deleteDialog = false">Cancel</v-btn>
          <v-btn color="error" variant="flat" @click="handleDelete">Delete</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()
const apiCycles = ref([])
const apiLoading = ref(false)


const formatDate = (dateStr) => {
  if (!dateStr) return '-'
  return dateStr.split('T')[0]
}


const fetchCyclesFromAPI = async () => {
  apiLoading.value = true
  try {
    const response = await fetch('https://localhost:7049/api/TestCycles')
    if (!response.ok) throw new Error('Failed to fetch data from the API')
    apiCycles.value = await response.json()
  } catch (error) {
    console.error('Error API:', error)
  } finally {
    apiLoading.value = false
  }
}


const headers = [
  { title: 'Cycle ID', key: 'cycle_code', align: 'start' },
  { title: 'Version Tag', key: 'name', align: 'start' },
  { title: 'Department', key: 'department', align: 'start' },
  { title: 'Start Date', key: 'dt_start_formatted', align: 'start' },
  { title: 'End Date', key: 'dt_end_formatted', align: 'start' },
  { title: 'Status', key: 'status', align: 'start' },
  { title: 'Created Date', key: 'created_date_formatted', align: 'start' },
  { title: 'Created By', key: 'created_by_name', align: 'start' },
  { title: 'Assigned To', key: 'assigned_to_name', align: 'start' },
  { title: 'Total Cases', key: 'totalCases', align: 'start' },
  { title: 'Auto Rule', key: 'auto_assign_rule', align: 'start' },
  { title: 'Actions', key: 'actions', align: 'end', sortable: false }
]


const cyclesList = computed(() => {
  return apiCycles.value.map(cycle => ({
    ...cycle,
    cycle_code: cycle.cycle_code || 'CY-000',
    name: cycle.name || '-',
    department: cycle.department || '-',
    status: cycle.status || 'Active',
    auto_assign_rule: cycle.auto_assign_rule || 'None',
    created_by_name: cycle.created_by_name || 'System',
    assigned_to_name: cycle.assigned_to_name || 'Unassigned',
    dt_start_formatted: formatDate(cycle.dt_start),
    dt_end_formatted: formatDate(cycle.dt_end),
    created_date_formatted: formatDate(cycle.created_date)
  }))
})

const goToTestCases = (cycleId) => {
  if (cycleId) {
    router.push(`/test-cases?cycle=${cycleId}`)
  }
}


const versionTagOptions = ['v2.0.0 Pre-Launch UAT', 'Sprint 25 Regression', 'v1.5.0 Production']


const departmentOptions = [
  'PEM', 'ADGM', 'PMM', 'SMHR', 'PB8', 'PB7', 'PB4', 'PB10', 
  'MOTC', 'SOTC', 'AOE', 'PQA', 'SEIT', 'MGMT', 'OTR', 'SOIT', 
  'SOVS', 'PAPR', 'PMGM', 'PLFG', 'SOMT', 'SMMG', 'PB6', 'PRND', 
  'SETH', 'SEPC', 'SETT', 'PRDA', 'AIT', 'SOPA', 'SEGH', 'PLTB', 
  'PLTA', 'SEPH', 'SOGT', 'PB3', 'AMCA', 'PAPK', 'PB2', 'PTM', 
  'ARPD', 'PQC', 'SEVN', 'SOIP', 'SOVN', 'SEKA', 'PLOG', 'METH', 
  'SOKA', 'PLRM', 'AHR', 'AACT'
]

const autoAssignOptions = [
  { title: 'Default (Latest Active Cycle)', value: 'default_latest' },
  { title: 'By Module / Feature', value: 'by_module' },
  { title: 'By Priority', value: 'by_priority' },
  { title: 'By Department', value: 'by_department' },
  { title: 'No Auto-Assign (Manual)', value: 'none' }
]


const dialog = ref(false)
const isEditing = ref(false)
const deleteDialog = ref(false)
const deleteTarget = ref(null)

const cycleForm = ref({
  id: null,
  cycleId: '',
  name: '',
  department: '',
  dtStart: new Date().toISOString().substr(0, 10),
  dtEnd: new Date().toISOString().substr(0, 10),
  status: 'Active',
  createdDate: new Date().toISOString().substr(0, 10),
  autoAssignRule: 'none'
})


const openCreateDialog = () => {
  isEditing.value = false
  cycleForm.value = {
    id: null,
    cycleId: '', 
    name: '',
    department: '',
    dtStart: new Date().toISOString().substr(0, 10),
    dtEnd: new Date().toISOString().substr(0, 10),
    status: 'Active',
    createdDate: new Date().toISOString().substr(0, 10),
    autoAssignRule: 'none'
  }
  dialog.value = true
}

const openEditDialog = (item) => {
  isEditing.value = true
  cycleForm.value = {
    id: item.id,
    cycleId: item.cycle_code,
    name: item.name || '',
    department: item.department || '',
    dtStart: item.dt_start ? item.dt_start.split('T')[0] : new Date().toISOString().substr(0, 10),
    dtEnd: item.dt_end ? item.dt_end.split('T')[0] : new Date().toISOString().substr(0, 10),
    status: item.status || 'Active',
    createdDate: item.created_date ? item.created_date.split('T')[0] : new Date().toISOString().substr(0, 10),
    autoAssignRule: item.auto_assign_rule || 'none'
  }
  dialog.value = true
}


const saveCycle = async () => {
  if (!cycleForm.value.name) {
    alert("Please select a Version Tag!")
    return
  }

  const payload = {
    name: cycleForm.value.name,
    department: cycleForm.value.department || null,
    dt_start: cycleForm.value.dtStart || null,
    dt_end: cycleForm.value.dtEnd || null,
    status: cycleForm.value.status || 'Active',
    auto_assign_rule: cycleForm.value.autoAssignRule || null
  } 

  if (isEditing.value) {
    payload.id = cycleForm.value.id
    payload.cycle_code = cycleForm.value.cycleId
  }

  try {
    const url = isEditing.value 
      ? `https://localhost:7049/api/TestCycles/${cycleForm.value.id}`
      : 'https://localhost:7049/api/TestCycles'
    
    const response = await fetch(url, {
      method: isEditing.value ? 'PUT' : 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    })

    if (response.ok) {
      alert(isEditing.value ? 'Sucessfully updated' : 'Successfully saved to SQL Server!')
      dialog.value = false
      await fetchCyclesFromAPI()
    } else {
      const errorText = await response.text()
      alert(`Gagal simpan: ${errorText}`)
    }
  } catch (error) {
    console.error('Error saving cycle:', error)
    alert('Ralat sambungan ke API.')
  }
}

const handleDelete = async () => {
  if (!deleteTarget.value) return

  try {
    const response = await fetch(`https://localhost:7049/api/TestCycles/${deleteTarget.value.id}`, {
      method: 'DELETE'
    })

    if (response.ok) {
      alert('Successfully saved to SQL Server!')
      deleteDialog.value = false
      await fetchCyclesFromAPI()
    } else {
      alert('failed to delete')
    }
  } catch (error) {
    console.error('Error deleting:', error)
    alert('Connection error to API')
  }
}

const confirmDelete = (item) => {
  deleteTarget.value = item
  deleteDialog.value = true
}

const getStatusColor = (status) => {
  if (status === 'Active') return 'success'
  if (status === 'Completed') return 'info'
  return 'grey'
}

onMounted(async () => {
  await fetchCyclesFromAPI()
})
</script>

<style scoped>
.border-t {
  border-top: 1px solid #e2e8f0;
}
.cursor-pointer {
  cursor: pointer;
}
</style>